{% set name = "fair-esm" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fair-esm-{{ version }}.tar.gz
  sha256: 8aff3c7a978beef72d5fa36334ed3262dccbcb00dfa1cfa2f19f4d3953e2c87b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pytorch >=1.5

test:
  imports:
    - esm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/facebookresearch/esm
  summary: 'Evolutionary Scale Modeling (esm): Pretrained language models for proteins. From Facebook AI Research.'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
