{% set name = "fair-esm" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fair-esm-{{ version }}.tar.gz
  sha256: bb33101164bc9e23af1d66430851d5378ae257fa67be5ffd71511b40c79f4062

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pytorch >=1.5
    - biotite

test:
  imports:
    - esm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/facebookresearch/esm
  summary: 'Evolutionary Scale Modeling (esm): Pretrained language models for proteins. From Facebook AI Research.'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
